# Generated by Django 5.2.8 on 2026-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0024_shipment_shipment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Own'), (2, 'Third Party')], default=1, help_text='Whether the AWB number was generated by this system (Own) or entered manually from a third party'),
        ),
    ]
