# Generated by Django 5.2.8 on 2026-06-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportimport', '0025_shipment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_HK', 'In Transit to Hong Kong'), ('ARRIVED_AT_HK', 'Flight Landed in Hong Kong'), ('RECEIVED_AT_HK_WAREHOUSE', 'Received in Hong Kong Warehouse'), ('OUT_FOR_DELIVERY_HK', 'On the Way to Delivery'), ('DELIVERED_IN_HK', 'Delivered in Hong Kong'), ('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_UK', 'In Transit to United Kingdom'), ('ARRIVED_AT_UK', 'Flight Landed in United Kingdom'), ('RECEIVED_AT_UK_WAREHOUSE', 'Received in United Kingdom Warehouse'), ('OUT_FOR_DELIVERY_UK', 'On the Way to Delivery'), ('DELIVERED_IN_UK', 'Delivered in United Kingdom'), ('PENDING', 'PENDING'), ('BOOKED', 'Booked'), ('RECEIVED_AT_BD', 'Received at Bangladesh Warehouse'), ('READY_FOR_SORTING', 'Ready for Sorting'), ('BAGGED_FOR_EXPORT', 'Bagged for Export'), ('IN_EXPORT_MANIFEST', 'In Export Manifest'), ('HANDED_TO_AIRLINE', 'Handed to Airline'), ('IN_TRANSIT_TO_CN', 'In Transit to China'), ('ARRIVED_AT_CN', 'Flight Landed in China'), ('RECEIVED_AT_CN_WAREHOUSE', 'Received in China Warehouse'), ('OUT_FOR_DELIVERY_CN', 'On the Way to Delivery'), ('DELIVERED_IN_CN', 'Delivered in China'), ('EXCEPTION_DAMAGED', 'Exception - Damaged'), ('EXCEPTION_CUSTOMS_HOLD', 'Exception - Customs Hold'), ('RETURN_TO_SENDER', 'Return to Sender')], default='BOOKED', max_length=50),
        ),
    ]
